env = Environment()
env.Append(LINKFLAGS = ['-lOpenThreads', '-losg', '-losgDB', '-losgUtil', '-losgGA', '-losgViewer', '-losgShadow', '-losgWidget'])
env.Program(
	target = 'OsgViewer',
	source = ['DepencenciesTest.cpp'],
)